### ISSUE TITLE
Exception evaluating SpringEL expression: "_csrf.token"

### ISSUE THREAD

**Issue by berniegp** [thymeleaf/thymeleaf-spring#110]
I am trying out Thymeleaf 3 in my Spring Boot (1.3.5) application with Spring Security and getting an exception which did not happen in Thymeleaf 2.1.

My page template has this code:

```
<script type="text/javascript" th:inline="javascript">
app.config({
    csrf: [[ ${_csrf.token} ]],
});
</script>
```

The exception is thrown when a page is requested while the user **has no active session**. When a user has a session, there is no exception.

Stack trace:

```
org.thymeleaf.exceptions.TemplateInputException: An error happened during template parsing (template: "class path resource [templates/home.html]")
    at org.thymeleaf.templateparser.markup.AbstractMarkupTemplateParser.parse(AbstractMarkupTemplateParser.java:241)
    at org.thymeleaf.templateparser.markup.AbstractMarkupTemplateParser.parseStandalone(AbstractMarkupTemplateParser.java:100)
    at org.thymeleaf.engine.TemplateManager.parseAndProcess(TemplateManager.java:667)
    at org.thymeleaf.TemplateEngine.process(TemplateEngine.java:1087)
    at org.thymeleaf.TemplateEngine.process(TemplateEngine.java:1061)
    at org.thymeleaf.spring4.view.ThymeleafView.renderFragment(ThymeleafView.java:335)
    at org.thymeleaf.spring4.view.ThymeleafView.render(ThymeleafView.java:189)
    at org.springframework.web.servlet.DispatcherServlet.render(DispatcherServlet.java:1246)
    at org.springframework.web.servlet.DispatcherServlet.processDispatchResult(DispatcherServlet.java:1029)
    at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:973)
    at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:895)
    at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:967)
    at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:858)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:622)
    at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:843)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:292)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
    at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
    at org.springframework.boot.actuate.autoconfigure.EndpointWebMvcAutoConfiguration$ApplicationContextHeaderFilter.doFilterInternal(EndpointWebMvcAutoConfiguration.java:261)
    at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
    at org.springframework.boot.actuate.trace.WebRequestTraceFilter.doFilterInternal(WebRequestTraceFilter.java:115)
    at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
    at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:316)
    at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:126)
    at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:90)
    at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330)
    at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:114)
    at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330)
    at org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:122)
    at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330)
    at org.springframework.security.web.authentication.AnonymousAuthenticationFilter.doFilter(AnonymousAuthenticationFilter.java:111)
    at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330)
    at org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter.doFilter(SecurityContextHolderAwareRequestFilter.java:169)
    at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330)
    at org.springframework.security.web.savedrequest.RequestCacheAwareFilter.doFilter(RequestCacheAwareFilter.java:48)
    at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330)
    at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:205)
    at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330)
    at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:120)
    at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330)
    at org.springframework.security.web.csrf.CsrfFilter.doFilterInternal(CsrfFilter.java:96)
    at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
    at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330)
    at org.springframework.security.web.header.HeaderWriterFilter.doFilterInternal(HeaderWriterFilter.java:64)
    at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
    at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330)
    at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:91)
    at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330)
    at org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter.doFilterInternal(WebAsyncManagerIntegrationFilter.java:53)
    at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
    at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330)
    at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:213)
    at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:176)
    at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:346)
    at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:262)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
    at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:99)
    at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
    at org.springframework.web.filter.HttpPutFormContentFilter.doFilterInternal(HttpPutFormContentFilter.java:87)
    at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
    at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:77)
    at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
    at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:121)
    at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
    at org.springframework.boot.actuate.autoconfigure.MetricsFilter.doFilterInternal(MetricsFilter.java:103)
    at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
    at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:212)
    at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106)
    at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:502)
    at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:141)
    at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
    at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)
    at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:522)
    at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1095)
    at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:672)
    at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1502)
    at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1458)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
    at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
    at java.lang.Thread.run(Unknown Source)
Caused by: org.attoparser.ParseException: An error happened during template rendering
    at org.attoparser.MarkupParser.parseDocument(MarkupParser.java:393)
    at org.attoparser.MarkupParser.parse(MarkupParser.java:257)
    at org.thymeleaf.templateparser.markup.AbstractMarkupTemplateParser.parse(AbstractMarkupTemplateParser.java:230)
    ... 98 common frames omitted
Caused by: org.thymeleaf.exceptions.TemplateOutputException: An error happened during template rendering
    at org.thymeleaf.engine.OutputTemplateHandler.handleText(OutputTemplateHandler.java:75)
    at org.thymeleaf.engine.ProcessorTemplateHandler.handleText(ProcessorTemplateHandler.java:587)
    at org.thymeleaf.engine.Text.beHandled(Text.java:97)
    at org.thymeleaf.engine.Model.process(Model.java:282)
    at org.thymeleaf.engine.ProcessorTemplateHandler.handleOpenElement(ProcessorTemplateHandler.java:1567)
    at org.thymeleaf.engine.TemplateHandlerAdapterMarkupHandler.handleOpenElementEnd(TemplateHandlerAdapterMarkupHandler.java:304)
    at org.thymeleaf.templateparser.markup.InlinedOutputExpressionMarkupHandler$InlineMarkupAdapterPreProcessorHandler.handleOpenElementEnd(InlinedOutputExpressionMarkupHandler.java:278)
    at org.thymeleaf.standard.inline.OutputExpressionInlinePreProcessorHandler.handleOpenElementEnd(OutputExpressionInlinePreProcessorHandler.java:186)
    at org.thymeleaf.templateparser.markup.InlinedOutputExpressionMarkupHandler.handleOpenElementEnd(InlinedOutputExpressionMarkupHandler.java:124)
    at org.attoparser.HtmlElement.handleOpenElementEnd(HtmlElement.java:109)
    at org.attoparser.HtmlMarkupHandler.handleOpenElementEnd(HtmlMarkupHandler.java:297)
    at org.attoparser.MarkupEventProcessorHandler.handleOpenElementEnd(MarkupEventProcessorHandler.java:402)
    at org.attoparser.ParsingElementMarkupUtil.parseOpenElement(ParsingElementMarkupUtil.java:159)
    at org.attoparser.MarkupParser.parseBuffer(MarkupParser.java:710)
    at org.attoparser.MarkupParser.parseDocument(MarkupParser.java:301)
    ... 100 common frames omitted
Caused by: org.thymeleaf.exceptions.TemplateProcessingException: Exception evaluating SpringEL expression: "_csrf.token" (template: "base" - line 80, col 10)
    at org.thymeleaf.spring4.expression.SPELVariableExpressionEvaluator.evaluate(SPELVariableExpressionEvaluator.java:290)
    at org.thymeleaf.standard.expression.VariableExpression.executeVariableExpression(VariableExpression.java:165)
    at org.thymeleaf.standard.expression.SimpleExpression.executeSimple(SimpleExpression.java:66)
    at org.thymeleaf.standard.expression.Expression.execute(Expression.java:109)
    at org.thymeleaf.standard.expression.Expression.execute(Expression.java:138)
    at org.thymeleaf.standard.expression.Expression.execute(Expression.java:125)
    at org.thymeleaf.standard.processor.AbstractStandardExpressionAttributeTagProcessor.doProcess(AbstractStandardExpressionAttributeTagProcessor.java:82)
    at org.thymeleaf.processor.element.AbstractAttributeTagProcessor.doProcess(AbstractAttributeTagProcessor.java:74)
    at org.thymeleaf.processor.element.AbstractElementTagProcessor.process(AbstractElementTagProcessor.java:95)
    at org.thymeleaf.util.ProcessorConfigurationUtils$ElementTagProcessorWrapper.process(ProcessorConfigurationUtils.java:633)
    at org.thymeleaf.engine.ProcessorTemplateHandler.handleOpenElement(ProcessorTemplateHandler.java:1304)
    at org.thymeleaf.engine.OpenElementTag.beHandled(OpenElementTag.java:205)
    at org.thymeleaf.engine.TemplateModel.process(TemplateModel.java:136)
    at org.thymeleaf.engine.TemplateManager.process(TemplateManager.java:520)
    at org.thymeleaf.util.LazyProcessingCharSequence.writeUnresolved(LazyProcessingCharSequence.java:85)
    at org.thymeleaf.util.AbstractLazyCharSequence.write(AbstractLazyCharSequence.java:103)
    at org.thymeleaf.engine.AbstractTextualTemplateEvent.writeContent(AbstractTextualTemplateEvent.java:224)
    at org.thymeleaf.engine.Text.write(Text.java:78)
    at org.thymeleaf.engine.OutputTemplateHandler.handleText(OutputTemplateHandler.java:71)
    ... 114 common frames omitted
Caused by: org.springframework.expression.spel.SpelEvaluationException: EL1021E:(pos 0): A problem occurred whilst attempting to access the property 'token': 'Unable to access property 'token' through getter method'
    at org.springframework.expression.spel.ast.PropertyOrFieldReference.readProperty(PropertyOrFieldReference.java:216)
    at org.springframework.expression.spel.ast.PropertyOrFieldReference.getValueInternal(PropertyOrFieldReference.java:94)
    at org.springframework.expression.spel.ast.PropertyOrFieldReference.access$000(PropertyOrFieldReference.java:46)
    at org.springframework.expression.spel.ast.PropertyOrFieldReference$AccessorLValue.getValue(PropertyOrFieldReference.java:374)
    at org.springframework.expression.spel.ast.CompoundExpression.getValueInternal(CompoundExpression.java:88)
    at org.springframework.expression.spel.ast.SpelNodeImpl.getValue(SpelNodeImpl.java:120)
    at org.springframework.expression.spel.standard.SpelExpression.getValue(SpelExpression.java:267)
    at org.thymeleaf.spring4.expression.SPELVariableExpressionEvaluator.evaluate(SPELVariableExpressionEvaluator.java:263)
    ... 132 common frames omitted
Caused by: org.springframework.expression.AccessException: Unable to access property 'token' through getter method
    at org.springframework.expression.spel.support.ReflectivePropertyAccessor$OptimalPropertyAccessor.read(ReflectivePropertyAccessor.java:629)
    at org.springframework.expression.spel.ast.PropertyOrFieldReference.readProperty(PropertyOrFieldReference.java:211)
    ... 139 common frames omitted
Caused by: java.lang.reflect.InvocationTargetException: null
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at org.springframework.expression.spel.support.ReflectivePropertyAccessor$OptimalPropertyAccessor.read(ReflectivePropertyAccessor.java:625)
    ... 140 common frames omitted
Caused by: java.lang.IllegalStateException: Cannot create a session after the response has been committed
    at org.apache.catalina.connector.Request.doGetSession(Request.java:2928)
    at org.apache.catalina.connector.Request.getSession(Request.java:2298)
    at org.apache.catalina.connector.RequestFacade.getSession(RequestFacade.java:895)
    at org.apache.catalina.connector.RequestFacade.getSession(RequestFacade.java:907)
    at javax.servlet.http.HttpServletRequestWrapper.getSession(HttpServletRequestWrapper.java:240)
    at javax.servlet.http.HttpServletRequestWrapper.getSession(HttpServletRequestWrapper.java:240)
    at org.springframework.security.web.csrf.HttpSessionCsrfTokenRepository.saveToken(HttpSessionCsrfTokenRepository.java:64)
    at org.springframework.security.web.csrf.CsrfFilter$SaveOnAccessCsrfToken.saveTokenIfNecessary(CsrfFilter.java:227)
    at org.springframework.security.web.csrf.CsrfFilter$SaveOnAccessCsrfToken.getToken(CsrfFilter.java:185)
    ... 145 common frames omitted
```

I think the very last exception is the most relevant:

> Caused by: java.lang.IllegalStateException: Cannot create a session after the response has been committed

Evaluating the SpEL expression `_csrf.token` causes a session to be created if there is not one already.

I suspect that the new _Throttled template execution_ (https://github.com/thymeleaf/thymeleaf/issues/487) which does "not start processing the template until the output channels are ready to transmit output" causes this error. In Thymeleaf 2, the response was not committed when the template was processed while in Thymeleaf 3, the template is processed much later when the response is committed.

There might also be other expressions or dialects which have side-effects that are completely incompatible with this new (late) template processing model.

**Comment by berniegp** [comment]
I use this workaround for now:

```
<script type="text/javascript" th:inline="javascript">
app.config({
    [# th:if="${hasSession}"]
    csrf: [[ ${_csrf.token} ]],
    [/]
});
</script>
```

with hasSession populated with:

```
model.addAttribute("hasSession", httpServletRequest.getSession(false) != null);
```

**Comment by berniegp** [comment]
When Thymeleaf automatically adds a hidden CSRF input field to a form, there is no problem with creating a session by trying to access the CSRF token value.

I assume this ordering of processors (and pre and posti processors) is by design so as to avoid writing to the http response too soon. I'm still posting some more details in case this case only works by chance rather than by design.

Stack trace (shortened) when the CSRF token is accessed for populating the hidden csrf input:

```
HttpSessionCsrfTokenRepository.saveToken(CsrfToken, HttpServletRequest, HttpServletResponse) line: 57   
CsrfFilter$SaveOnAccessCsrfToken.saveTokenIfNecessary() line: 227   
CsrfFilter$SaveOnAccessCsrfToken.getToken() line: 185   
CsrfRequestDataValueProcessor.getExtraHiddenFields(HttpServletRequest) line: 71 
RequestDataValueProcessor4Delegate.getExtraHiddenFields(RequestContext, HttpServletRequest) line: 86    
RequestDataValueProcessorUtils.getExtraHiddenFields(ITemplateContext) line: 155 
SpringActionTagProcessor.doProcess(ITemplateContext, IProcessableElementTag, AttributeName, String, Object, IElementTagStructureHandler) line: 116  
SpringActionTagProcessor(AbstractStandardExpressionAttributeTagProcessor).doProcess(ITemplateContext, IProcessableElementTag, AttributeName, String, IElementTagStructureHandler) line: 98  
SpringActionTagProcessor(AbstractAttributeTagProcessor).doProcess(ITemplateContext, IProcessableElementTag, IElementTagStructureHandler) line: 74   
SpringActionTagProcessor(AbstractElementTagProcessor).process(ITemplateContext, IProcessableElementTag, IElementTagStructureHandler) line: 95   
ProcessorConfigurationUtils$ElementTagProcessorWrapper.process(ITemplateContext, IProcessableElementTag, IElementTagStructureHandler) line: 633 
ProcessorTemplateHandler.handleOpenElement(IOpenElementTag) line: 1304  
TemplateHandlerAdapterMarkupHandler.handleOpenElementEnd(char[], int, int, int, int) line: 304  
InlinedOutputExpressionMarkupHandler$InlineMarkupAdapterPreProcessorHandler.handleOpenElementEnd(char[], int, int, int, int) line: 278  
OutputExpressionInlinePreProcessorHandler.handleOpenElementEnd(char[], int, int, int, int) line: 186    
InlinedOutputExpressionMarkupHandler.handleOpenElementEnd(char[], int, int, int, int) line: 124 
HtmlBodyBlockElement(HtmlElement).handleOpenElementEnd(char[], int, int, int, int, IMarkupHandler, ParseStatus, boolean, boolean) line: 109 
HtmlMarkupHandler.handleOpenElementEnd(char[], int, int, int, int) line: 297    
MarkupEventProcessorHandler.handleOpenElementEnd(char[], int, int, int, int) line: 402  
ParsingElementMarkupUtil.parseOpenElement(char[], int, int, int, int, IMarkupHandler) line: 159 
MarkupParser.parseBuffer(char[], int, int, IMarkupHandler, ParseStatus) line: 710   
MarkupParser.parseDocument(Reader, int, IMarkupHandler, ParseStatus) line: 301  
MarkupParser.parse(Reader, IMarkupHandler) line: 257    
HTMLTemplateParser(AbstractMarkupTemplateParser).parse(IEngineConfiguration, String, String, Set<String>, ITemplateResource, int, int, TemplateMode, boolean, ITemplateHandler) line: 230   
HTMLTemplateParser(AbstractMarkupTemplateParser).parseStandalone(IEngineConfiguration, String, String, Set<String>, ITemplateResource, TemplateMode, boolean, ITemplateHandler) line: 100   
TemplateManager.parseAndProcess(TemplateSpec, IContext, Writer) line: 667   
SpringTemplateEngine(TemplateEngine).process(TemplateSpec, IContext, Writer) line: 1087 
SpringTemplateEngine(TemplateEngine).process(String, Set<String>, IContext, Writer) line: 1061  
ThymeleafView.renderFragment(Set<String>, Map<String,?>, HttpServletRequest, HttpServletResponse) line: 335 
ThymeleafView.render(Map<String,?>, HttpServletRequest, HttpServletResponse) line: 189  
DispatcherServlet.render(ModelAndView, HttpServletRequest, HttpServletResponse) line: 1246  
DispatcherServlet.processDispatchResult(HttpServletRequest, HttpServletResponse, HandlerExecutionChain, ModelAndView, Exception) line: 1029 
DispatcherServlet.doDispatch(HttpServletRequest, HttpServletResponse) line: 973 
DispatcherServlet.doService(HttpServletRequest, HttpServletResponse) line: 895  
DispatcherServlet(FrameworkServlet).processRequest(HttpServletRequest, HttpServletResponse) line: 967   
DispatcherServlet(FrameworkServlet).doGet(HttpServletRequest, HttpServletResponse) line: 858    
DispatcherServlet(HttpServlet).service(HttpServletRequest, HttpServletResponse) line: 622   
DispatcherServlet(FrameworkServlet).service(HttpServletRequest, HttpServletResponse) line: 843  
DispatcherServlet(HttpServlet).service(ServletRequest, ServletResponse) line: 729   
```

**Comment by danielfernandez** [comment]
It's not exactly _engine throttling_ that is causing this. Throttling is only used in _reactive_ environments, and Spring Boot isn't one.

However, it has to do with the new architecture: Thymeleaf's new architecture tries to reduce latency to the minimum by producing template output as the template is being processed. So by the time it reaches your `<script>` tag, output for the part of your template that goes before that tag will have already been generated, potentially having caused the web server's output buffer to fill and therefore to flush towards the client. This is why, when the offending code is executed, the web server considers your response to have already been _committed_ and therefore does fail when your code tries to create a new session.

I'm afraid this is an architectural constraint (actually, it's the way most other template engines work). In v2.1, all output was generated in memory before output started to be produced, and therefore this scenario would never happen. However, this was changed because latency-wise it was at best obviously _"sub-optimal"_.

If your workaround works for you --if you don't really have to create any new sessions there--, I'd stick to it as a valid fix. Actually, not creating sessions if you don't need them will certainly benefit your applications performance and memory usage.

If you really need to create sessions at that point in your template, I'd try to move that fragment of code further up in the template in order to avoid the _response already committed_ part, or if that is not possible, create a _post-processor_ (see `org.thymeleaf.postprocessor.IPostProcessor`: http://www.thymeleaf.org/apidocs/thymeleaf/3.0.0.RELEASE/org/thymeleaf/postprocessor/IPostProcessor.html ) that simply caches all the events launched by the engine in a `List<ITemplateEvent>`, and sends them all to output when the `ITemplateEnd` event is received (when execution is finished). That will make v3.0 emulate the behaviour in v2.1 --not creating output until all processing has been done--, but of course you'd lose an important part of the performance advantage of Thymeleaf 3.

Oh, and an even easier solution would be to process your template into a `String` by calling the `TemplateEngine` directly, and then writing that `String` to output. Or, instead, tweaking the `HttpServletResponse#getWriter` (by adding a web filter like URL-rewriting filters do) so that the writer caches all the output before sending to the real response writer.

**Comment by berniegp** [comment]
Thank you for the detailed explanation.

Since we posted our comments at about the same time, I'll ask this bit again. Is there a potential problem with the hidden csrf field added to forms? Is everything wired up so the response is not written to before the csrf token value is accessed?

My simple test (login form) shows that it works fine, but I can certainly have missed an error condition.

p.s. Before encountering this issue, I had not realized that I was needlessly creating sessions. You are of indeed right that it's better to avoid creating sessions if possible.

**Comment by berniegp** [comment]
To rephrase my last question, this worries me from https://github.com/thymeleaf/thymeleaf/issues/389

> In order to achieve these goals, Thymeleaf 3.0 abandons most of its DOM-oriented processing mechanisms and turns into an event-based template processor that responds to template parser/cache events by processing the template markup or text and **immediately producing its output, even before new events coming from input for the same template are processed**.

If some output was written to the response (from a previous element block) before the template processor gets to a `<form>` element (to which is appended a hidden csrf field), it seems to me that the same error can occur.

**Comment by danielfernandez** [comment]
I understand. The basic _repository strategy_ for storing the CSRF token between HTTP requests in Spring Security involves using an `HttpSession`, so in some sense an application using CSRF protection should be already creating sessions for its users/visitors as a security requirement (unless there is a _stateless_ part of the application, like seems to be your case, which in this case will probably go CSRF-unprotected). Anyway, the view layer doesn't seem like the right place to create user sessions in most cases.

Thymeleaf however does not deal with CSRF tokens. All it does is ask Spring Web's (not Spring Security's) `RequestDataValueProcessor` mechanism whether it should include any additional _hidden fields_ inside a form. If this mechanism answers _yes_ it will provide Thymeleaf with the fields to be added, but at no point Thymeleaf has any specific code for CSRF or understands the specificities of CSRF-handling. It's simply that Spring Security injects itself into this `RequestDataValueProcessor` mechanism and makes it return the CSRF-related fields, including its token. This is completely transparent to Thymeleaf.

It is therefore the responsibility of Spring Security or the application developer to make sure that when Thymeleaf reaches the point of having to write a CSRF token, a session already exists (or a different token-storing strategy not involving the session is being used).

Actually, this behaviour in Thymeleaf is completely equivalent to what Spring's own JSP tag library does (see `org.springframework.web.servlet.tags.form.FormTag`). No CSRF-specific code there either. If a session is created at this point it is a (maybe undesired) lateral effect. And JSP also writes output as the template is processed, so the scenario is equivalent to that of Thymeleaf.

**Comment by berniegp** [comment]
What could be called the "stateless" part of the application is the login form. I say stateless because it's accessible without a session, but In fact, it's not really stateless since it's protected by CSRF which triggers the creation of a session. Something somewhere has to trigger the first session creation.

In my tests, I found 2 conditions which trigger output flushing which in turn marks the response as "committed":
1. Having 16kb in the buffer (with Spring Boot embedded Tomcat)
2. Thymeleaf's inline serializing uses Jackson. Jackson flushes its buffer after serialization.

(this list is probably not exhaustive)

So it seems, I will indeed need to ensure a session is present in the login controller (the GET part) instead of having it implicitly created when requesting the CSRF token value.

I guess this issue can be closed then. Thanks for your insight.

**Comment by alexradul** [comment]
An easy workaround for this issue is given here; https://stackoverflow.com/a/53004917/5366876
