### ISSUE TITLE
NoSuchMethodError when creating TemplateEngine (com.fasterxml.jackson.databind.ObjectMapper.disable(...))

### ISSUE THREAD

**Issue by hiddewie** [thymeleaf/thymeleaf-spring#116]
I have a problem using Spring 4, together with Tymeleaf 3.0.0 and Thymleaf-Spring.

When loading a new Template engine, a `SpringStandardDialect` is created, which in turn creates a `StandardDialect`. This object creates a Javascript serializer (`new StandardJavaScriptSerializer(true)`) which uses the `true` argument to use the Jackson serialization classes, if possible. 

The Jackson library has been loaded (version 1.8.0 as determined by Gradle), and the `disable(JsonGenerator$Feature)` method seems to be present in the byte code (decompiled classes).

```
Caused by: java.lang.NoSuchMethodError: com.fasterxml.jackson.databind.ObjectMapper.disable([Lcom/fasterxml/jackson/core/JsonGenerator$Feature;)Lcom/fasterxml/jackson/databind/ObjectMapper;
        at org.thymeleaf.standard.serializer.StandardJavaScriptSerializer$JacksonStandardJavaScriptSerializer.<init>(StandardJavaScriptSerializer.java:124)
        at org.thymeleaf.standard.serializer.StandardJavaScriptSerializer.<init>(StandardJavaScriptSerializer.java:96)
        at org.thymeleaf.standard.StandardDialect.<init>(StandardDialect.java:134)
        at org.thymeleaf.spring4.dialect.SpringStandardDialect.<init>(SpringStandardDialect.java:102)
        at org.thymeleaf.spring4.SpringTemplateEngine.<clinit>(SpringTemplateEngine.java:63)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) [rt.jar:1.8.0_25]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) [rt.jar:1.8.0_25]
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) [rt.jar:1.8.0_25]
        at java.lang.reflect.Constructor.newInstance(Constructor.java:408) [rt.jar:1.8.0_25]
        at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:147)
        at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:89)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateBean(AbstractAutowireCapableBeanFactory.java:1098)
        ... 40 more
```

Part of my gradle configuration:

```
        // Tiles
        compile 'org.apache.tiles:tiles-portlet:2.2.2'
        compile 'org.apache.tiles:tiles-servlet:2.2.2'
        compile('org.apache.tiles:tiles-core:2.2.2') { force = true }
        compile('org.apache.tiles:tiles-jsp:2.2.2') { force = true }
        // Struts
        compile('org.apache.struts:struts2-core:2.3.16.3') { force = true }
        compile('org.apache.struts:struts2-dojo-plugin:2.3.16.3') { force = true }
        compile 'org.apache.struts:struts2-tiles-plugin:2.3.16.3'

        // Spring
        compile 'org.springframework:spring-webmvc:4.3.1.RELEASE'

        // Thymeleaf
        compile 'org.thymeleaf:thymeleaf:3.0.0.RELEASE'
        compile 'org.thymeleaf:thymeleaf-spring4:3.0.0.RELEASE'
        compile 'org.thymeleaf.extras:thymeleaf-extras-tiles2:2.1.1.RELEASE'
        compile 'org.thymeleaf.extras:thymeleaf-extras-tiles2-spring4:2.1.1.RELEASE'
```

The Struts code library is there for backward compatible reasons. 

Part of `web.xml`:

```
<bean id="htmlTemplateResolver" class="org.thymeleaf.spring4.templateresolver.SpringResourceTemplateResolver">
        <property name="prefix" value="/WEB-INF/templates/" />
        <property name="suffix" value=".html" />
        <property name="templateMode" value="HTML" />
        <property name="cacheable" value="false" /> <!-- Development only -->
    </bean>
    <bean id="jsTemplateResolver" class="org.thymeleaf.spring4.templateresolver.SpringResourceTemplateResolver">
        <property name="prefix" value="/WEB-INF/templates/" />
        <property name="suffix" value=".js" />
        <property name="templateMode" value="JAVASCRIPT" />
        <property name="cacheable" value="false" /> <!-- Development only -->
    </bean>
    <bean id="cssTemplateResolver" class="org.thymeleaf.spring4.templateresolver.SpringResourceTemplateResolver">
        <property name="prefix" value="/WEB-INF/templates/" />
        <property name="suffix" value=".css" />
        <property name="templateMode" value="CSS" />
        <property name="cacheable" value="false" /> <!-- Development only -->
    </bean>

    <bean id="htmlViewResolver" class="org.thymeleaf.spring4.view.ThymeleafViewResolver">
        <property name="viewClass" value="org.thymeleaf.extras.tiles2.spring4.web.view.ThymeleafTilesView"/>
        <property name="templateEngine" ref="htmlTemplateEngine" />
        <property name="characterEncoding" value="UTF-8" />
    </bean>
    <bean id="jsViewResolver" class="org.thymeleaf.spring4.view.ThymeleafViewResolver">
        <property name="viewClass" value="org.thymeleaf.extras.tiles2.spring4.web.view.ThymeleafTilesView"/>
        <property name="templateEngine" ref="jsTemplateEngine" />
        <property name="characterEncoding" value="UTF-8" />
    </bean>
    <bean id="cssViewResolver" class="org.thymeleaf.spring4.view.ThymeleafViewResolver">
        <property name="viewClass" value="org.thymeleaf.extras.tiles2.spring4.web.view.ThymeleafTilesView"/>
        <property name="templateEngine" ref="cssTemplateEngine" />
        <property name="characterEncoding" value="UTF-8" />
    </bean>

    <bean id="tilesConfigurer" class="org.thymeleaf.extras.tiles2.spring4.web.configurer.ThymeleafTilesConfigurer">
        <property name="definitions">
            <list>
                <value>/WEB-INF/tiles.xml</value>
            </list>
        </property>
    </bean>

    <bean id="htmlTemplateEngine" class="org.thymeleaf.spring4.SpringTemplateEngine">
        <property name="templateResolver" ref="htmlTemplateResolver" />
        <property name="additionalDialects">
            <set>
                <bean class="org.thymeleaf.extras.tiles2.dialect.TilesDialect"/>
            </set>
        </property>
    </bean>
    <bean id="jsTemplateEngine" class="org.thymeleaf.spring4.SpringTemplateEngine">
        <property name="templateResolver" ref="jsTemplateResolver" />
        <property name="additionalDialects">
            <set>
                <bean class="org.thymeleaf.extras.tiles2.dialect.TilesDialect"/>
            </set>
        </property>
    </bean>
    <bean id="cssTemplateEngine" class="org.thymeleaf.spring4.SpringTemplateEngine">
        <property name="templateResolver" ref="cssTemplateResolver" />
        <property name="additionalDialects">
            <set>
                <bean class="org.thymeleaf.extras.tiles2.dialect.TilesDialect"/>
            </set>
        </property>
    </bean>
```

I've also tried with forced lower versions (2.6 and 2.7) of the Jackson library. 

Do you have any help? Thank you in advance.

If at all possible (I have so far found no way to do this), it would be great to simply disable the `JacksonStandardJavaScriptSerializer` in `StandardJavaScriptSerializer`, by setting useJacksonIfAvailable to `false`.

**Comment by danielfernandez** [comment]
Please note 1.8.0 is a quite old version of Jackson. Thymeleaf will need at least version 2.5.0, and it should perfectly initialise in these cases (the method you cite was actually added in that specific version).

I've also added thymeleaf/thymeleaf#520 in order to improve error reporting in this kind of scenario.

**Comment by hiddewie** [comment]
Thank you, that clears things up. 

It might be the default JBoss libraries that are included in my deployment.
