### ISSUE TITLE
NoSuchMethodError in ThymeleafReactiveViewResolver loadView

### ISSUE THREAD

**Issue by kafji** [thymeleaf/thymeleaf-spring#146]
Using Spring WebFlux to render HTML template with Thymeleaf produce NoSuchMethodError.

How to reproduce:
With Spring Boot 2.0.0.M2, respond a request with `ServerResponse.ok().render("index")`.
Complete example: https://github.com/kafji/thymeleafnosuchmethod.

Stacktrace:
```
java.lang.NoSuchMethodError: org.thymeleaf.spring5.view.reactive.ThymeleafReactiveViewResolver.getApplicationContext()Lorg/springframework/context/ApplicationContext;
	at org.thymeleaf.spring5.view.reactive.ThymeleafReactiveViewResolver.loadView(ThymeleafReactiveViewResolver.java:581) ~[thymeleaf-spring5-3.0.6.M4.jar:3.0.6.M4]
	at org.thymeleaf.spring5.view.reactive.ThymeleafReactiveViewResolver.resolveViewName(ThymeleafReactiveViewResolver.java:569) ~[thymeleaf-spring5-3.0.6.M4.jar:3.0.6.M4]
	at org.springframework.web.reactive.result.view.ViewResolutionResultHandler.lambda$resolveViews$2(ViewResolutionResultHandler.java:272) ~[spring-webflux-5.0.0.RC2.jar:5.0.0.RC2]
	at reactor.core.publisher.FluxConcatMap$ConcatMapImmediate.drain(FluxConcatMap.java:350) ~[reactor-core-3.1.0.M2.jar:3.1.0.M2]
	at reactor.core.publisher.FluxConcatMap$ConcatMapImmediate.onSubscribe(FluxConcatMap.java:205) ~[reactor-core-3.1.0.M2.jar:3.1.0.M2]
	at reactor.core.publisher.FluxIterable.subscribe(FluxIterable.java:89) ~[reactor-core-3.1.0.M2.jar:3.1.0.M2]
	at reactor.core.publisher.FluxIterable.subscribe(FluxIterable.java:54) ~[reactor-core-3.1.0.M2.jar:3.1.0.M2]
	at reactor.core.publisher.FluxConcatMap.subscribe(FluxConcatMap.java:117) ~[reactor-core-3.1.0.M2.jar:3.1.0.M2]
	at reactor.core.publisher.MonoCollectList.subscribe(MonoCollectList.java:57) ~[reactor-core-3.1.0.M2.jar:3.1.0.M2]
	at reactor.core.publisher.MonoMapFuseable.subscribe(MonoMapFuseable.java:59) ~[reactor-core-3.1.0.M2.jar:3.1.0.M2]
	at reactor.core.publisher.MonoFlatMap.subscribe(MonoFlatMap.java:59) ~[reactor-core-3.1.0.M2.jar:3.1.0.M2]
	at reactor.core.publisher.MonoFlatMap$ThenMapMain.onNext(MonoFlatMap.java:146) ~[reactor-core-3.1.0.M2.jar:3.1.0.M2]
	at reactor.core.publisher.FluxSwitchIfEmpty$SwitchIfEmptySubscriber.onNext(FluxSwitchIfEmpty.java:67) ~[reactor-core-3.1.0.M2.jar:3.1.0.M2]
	at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onNext(FluxMapFuseable.java:115) ~[reactor-core-3.1.0.M2.jar:3.1.0.M2]
	at reactor.core.publisher.Operators$ScalarSubscription.request(Operators.java:1472) ~[reactor-core-3.1.0.M2.jar:3.1.0.M2]
	at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.request(FluxMapFuseable.java:156) ~[reactor-core-3.1.0.M2.jar:3.1.0.M2]
	at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.set(Operators.java:1288) ~[reactor-core-3.1.0.M2.jar:3.1.0.M2]
	at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.onSubscribe(Operators.java:1162) ~[reactor-core-3.1.0.M2.jar:3.1.0.M2]
	at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onSubscribe(FluxMapFuseable.java:90) ~[reactor-core-3.1.0.M2.jar:3.1.0.M2]
	at reactor.core.publisher.MonoJust.subscribe(MonoJust.java:54) ~[reactor-core-3.1.0.M2.jar:3.1.0.M2]
	at reactor.core.publisher.MonoMapFuseable.subscribe(MonoMapFuseable.java:59) ~[reactor-core-3.1.0.M2.jar:3.1.0.M2]
	at reactor.core.publisher.MonoSwitchIfEmpty.subscribe(MonoSwitchIfEmpty.java:44) ~[reactor-core-3.1.0.M2.jar:3.1.0.M2]
	at reactor.core.publisher.MonoFlatMap.subscribe(MonoFlatMap.java:59) ~[reactor-core-3.1.0.M2.jar:3.1.0.M2]
	at reactor.core.publisher.MonoOnErrorResume.subscribe(MonoOnErrorResume.java:44) ~[reactor-core-3.1.0.M2.jar:3.1.0.M2]
	at reactor.core.publisher.MonoFlatMap$ThenMapMain.onNext(MonoFlatMap.java:146) ~[reactor-core-3.1.0.M2.jar:3.1.0.M2]
	at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:919) ~[reactor-core-3.1.0.M2.jar:3.1.0.M2]
	at reactor.core.publisher.MonoFlatMap$ThenMapInner.onNext(MonoFlatMap.java:229) ~[reactor-core-3.1.0.M2.jar:3.1.0.M2]
	at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:919) ~[reactor-core-3.1.0.M2.jar:3.1.0.M2]
	at reactor.core.publisher.MonoThenIgnore$ThenAcceptInner.onNext(MonoThenIgnore.java:276) ~[reactor-core-3.1.0.M2.jar:3.1.0.M2]
	at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onNext(FluxOnErrorResume.java:72) ~[reactor-core-3.1.0.M2.jar:3.1.0.M2]
	at reactor.core.publisher.FluxPeekFuseable$PeekFuseableSubscriber.onNext(FluxPeekFuseable.java:185) ~[reactor-core-3.1.0.M2.jar:3.1.0.M2]
	at reactor.core.publisher.Operators$ScalarSubscription.request(Operators.java:1472) ~[reactor-core-3.1.0.M2.jar:3.1.0.M2]
	at reactor.core.publisher.FluxPeekFuseable$PeekFuseableSubscriber.request(FluxPeekFuseable.java:128) ~[reactor-core-3.1.0.M2.jar:3.1.0.M2]
	at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.set(Operators.java:1288) ~[reactor-core-3.1.0.M2.jar:3.1.0.M2]
	at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onSubscribe(FluxOnErrorResume.java:67) ~[reactor-core-3.1.0.M2.jar:3.1.0.M2]
	at reactor.core.publisher.FluxPeekFuseable$PeekFuseableSubscriber.onSubscribe(FluxPeekFuseable.java:161) ~[reactor-core-3.1.0.M2.jar:3.1.0.M2]
	at reactor.core.publisher.FluxFlatMap.trySubscribeScalarMap(FluxFlatMap.java:160) ~[reactor-core-3.1.0.M2.jar:3.1.0.M2]
	at reactor.core.publisher.MonoFlatMap.subscribe(MonoFlatMap.java:52) ~[reactor-core-3.1.0.M2.jar:3.1.0.M2]
	at reactor.core.publisher.MonoPeekFuseable.subscribe(MonoPeekFuseable.java:77) ~[reactor-core-3.1.0.M2.jar:3.1.0.M2]
	at reactor.core.publisher.MonoOnErrorResume.subscribe(MonoOnErrorResume.java:44) ~[reactor-core-3.1.0.M2.jar:3.1.0.M2]
	at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:53) ~[reactor-core-3.1.0.M2.jar:3.1.0.M2]
	at reactor.core.publisher.MonoThenIgnore$ThenIgnoreMain.drain(MonoThenIgnore.java:147) ~[reactor-core-3.1.0.M2.jar:3.1.0.M2]
	at reactor.core.publisher.MonoThenIgnore.subscribe(MonoThenIgnore.java:55) ~[reactor-core-3.1.0.M2.jar:3.1.0.M2]
	at reactor.core.publisher.MonoFlatMap$ThenMapMain.onNext(MonoFlatMap.java:146) ~[reactor-core-3.1.0.M2.jar:3.1.0.M2]
	at reactor.core.publisher.FluxSwitchIfEmpty$SwitchIfEmptySubscriber.onNext(FluxSwitchIfEmpty.java:67) ~[reactor-core-3.1.0.M2.jar:3.1.0.M2]
	at reactor.core.publisher.MonoNext$NextSubscriber.onNext(MonoNext.java:76) ~[reactor-core-3.1.0.M2.jar:3.1.0.M2]
	at reactor.core.publisher.FluxConcatMap$ConcatMapImmediate.innerNext(FluxConcatMap.java:265) ~[reactor-core-3.1.0.M2.jar:3.1.0.M2]
	at reactor.core.publisher.FluxConcatMap$ConcatMapInner.onNext(FluxConcatMap.java:767) ~[reactor-core-3.1.0.M2.jar:3.1.0.M2]
	at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onNext(FluxMapFuseable.java:115) ~[reactor-core-3.1.0.M2.jar:3.1.0.M2]
	at reactor.core.publisher.Operators$ScalarSubscription.request(Operators.java:1472) ~[reactor-core-3.1.0.M2.jar:3.1.0.M2]
	at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.request(FluxMapFuseable.java:156) ~[reactor-core-3.1.0.M2.jar:3.1.0.M2]
	at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.set(Operators.java:1288) ~[reactor-core-3.1.0.M2.jar:3.1.0.M2]
	at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.onSubscribe(Operators.java:1162) ~[reactor-core-3.1.0.M2.jar:3.1.0.M2]
	at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onSubscribe(FluxMapFuseable.java:90) ~[reactor-core-3.1.0.M2.jar:3.1.0.M2]
	at reactor.core.publisher.MonoJust.subscribe(MonoJust.java:54) ~[reactor-core-3.1.0.M2.jar:3.1.0.M2]
	at reactor.core.publisher.MonoMapFuseable.subscribe(MonoMapFuseable.java:59) ~[reactor-core-3.1.0.M2.jar:3.1.0.M2]
	at reactor.core.publisher.FluxConcatMap$ConcatMapImmediate.drain(FluxConcatMap.java:409) ~[reactor-core-3.1.0.M2.jar:3.1.0.M2]
	at reactor.core.publisher.FluxConcatMap$ConcatMapImmediate.onSubscribe(FluxConcatMap.java:205) ~[reactor-core-3.1.0.M2.jar:3.1.0.M2]
	at reactor.core.publisher.FluxIterable.subscribe(FluxIterable.java:89) ~[reactor-core-3.1.0.M2.jar:3.1.0.M2]
	at reactor.core.publisher.FluxIterable.subscribe(FluxIterable.java:54) ~[reactor-core-3.1.0.M2.jar:3.1.0.M2]
	at reactor.core.publisher.FluxConcatMap.subscribe(FluxConcatMap.java:117) ~[reactor-core-3.1.0.M2.jar:3.1.0.M2]
	at reactor.core.publisher.MonoNext.subscribe(MonoNext.java:40) ~[reactor-core-3.1.0.M2.jar:3.1.0.M2]
	at reactor.core.publisher.MonoSwitchIfEmpty.subscribe(MonoSwitchIfEmpty.java:44) ~[reactor-core-3.1.0.M2.jar:3.1.0.M2]
	at reactor.core.publisher.MonoFlatMap.subscribe(MonoFlatMap.java:59) ~[reactor-core-3.1.0.M2.jar:3.1.0.M2]
	at reactor.core.publisher.MonoFlatMap.subscribe(MonoFlatMap.java:59) ~[reactor-core-3.1.0.M2.jar:3.1.0.M2]
	at reactor.core.publisher.MonoOnErrorResume.subscribe(MonoOnErrorResume.java:44) ~[reactor-core-3.1.0.M2.jar:3.1.0.M2]
	at reactor.core.publisher.MonoOnErrorResume.subscribe(MonoOnErrorResume.java:44) ~[reactor-core-3.1.0.M2.jar:3.1.0.M2]
	at reactor.core.publisher.MonoThenIgnore$ThenIgnoreMain.drain(MonoThenIgnore.java:165) ~[reactor-core-3.1.0.M2.jar:3.1.0.M2]
	at reactor.core.publisher.MonoThenIgnore.subscribe(MonoThenIgnore.java:55) ~[reactor-core-3.1.0.M2.jar:3.1.0.M2]
	at reactor.core.publisher.MonoOnErrorResume.subscribe(MonoOnErrorResume.java:44) ~[reactor-core-3.1.0.M2.jar:3.1.0.M2]
	at reactor.core.publisher.MonoPeekTerminal.subscribe(MonoPeekTerminal.java:60) ~[reactor-core-3.1.0.M2.jar:3.1.0.M2]
	at reactor.ipc.netty.channel.ChannelOperations.applyHandler(ChannelOperations.java:382) ~[reactor-netty-0.6.4.RELEASE.jar:0.6.4.RELEASE]
	at reactor.ipc.netty.http.server.HttpServerOperations.onHandlerStart(HttpServerOperations.java:354) ~[reactor-netty-0.6.4.RELEASE.jar:0.6.4.RELEASE]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163) ~[netty-common-4.1.12.Final.jar:4.1.12.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:403) [netty-common-4.1.12.Final.jar:4.1.12.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:462) [netty-transport-4.1.12.Final.jar:4.1.12.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858) [netty-common-4.1.12.Final.jar:4.1.12.Final]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_131]
```

**Comment by danielfernandez** [comment]
Yes, this is known and due to a breaking change in the Spring APIs from Spring Boot `2.0.0.M1` to `2.0.0.M2`. You need to modify the version of Thymeleaf (both `thymeleaf.version` and `thymeleaf-spring5.version`) to `3.0.7-SNAPSHOT`.
