### ISSUE TITLE
java.lang.StackOverflowError: null  thymeleaf.util.JavaScriptUtils.printObject(JavaScriptUtils.java:369)

### ISSUE THREAD

**Issue by alamhubb** [thymeleaf/thymeleaf-spring#170]
springboot version :1.5.9.RELEASE

My English is very poor, sorry, so I used Google translation.
//我英语很差,抱歉,所以我用了谷歌翻译

I use the spring data jpa, my two entities exist mutual references, so the following error, how can I solve?
//我使用了spring data jpa,我的两个 entity 存在互相引用的情况,所以出现了下方的错误,请问我该如何解决?
Why did I use @ JsonIgnore did not work it?
//为什么我使用了 @JsonIgnore 却没有起作用呢

@Entity
@JsonIgnoreProperties({"hibernateLazyInitializer", "handler"})
public class User {
    @Id
    @GeneratedValue
    Integer id;
    String name;
    @OneToMany(cascade = CascadeType.REFRESH)
    @JoinColumn(name = "user_id")
    @JsonIgnore
    Set<Shuo> shuos;

    @JsonIgnore
    public Set<Shuo> getShuos() {
        return shuos;
    }
    @JsonIgnore
    public void setShuos(Set<Shuo> shuos) {
        this.shuos = shuos;
    }

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }
}

@Entity
@JsonIgnoreProperties({"hibernateLazyInitializer", "handler"})
public class Shuo {
    @Id
    @GeneratedValue
    int id;
    String content;
    Date date;

    @ManyToOne(cascade = CascadeType.REFRESH)
    @JoinColumn(name = "user_id")//加入一列作为外键
    @JsonIgnore
    User user;
    @JsonIgnore
    public User getUser() {
        return user;
    }

    @JsonIgnore
    public void setUser(User user) {
        this.user = user;
    }

    @ManyToMany(cascade = CascadeType.REFRESH)
    Set<Tag> tags;

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public Set<Tag> getTags() {
        return tags;
    }

    public void setTags(Set<Tag> tags) {
        this.tags = tags;
    }

    public Date getDate() {
        return date;
    }

    public void setDate(Date date) {
        this.date = date;
    }

    public Shuo() {
    }

    public Shuo(String content, Date date) {
        this.content = content;
        this.date = date;
    }

    public String getContent() {
        return content;
    }

    public void setContent(String content) {
        this.content = content;
    }

}

Front-end code //前端代码:

if( [[${user}]] is exist ){

var app = new Vue({
        el: '#app',
        data: {
            user:[[${user}]]   If there is this code, it will be wrong.//如果这段代码存在就会报错
        },

java.lang.StackOverflowError: null
	at sun.reflect.misc.ReflectUtil.checkPackageAccess(ReflectUtil.java:164) ~[na:1.8.0_151]
	at sun.reflect.misc.ReflectUtil.isPackageAccessible(ReflectUtil.java:195) ~[na:1.8.0_151]
	at java.beans.Introspector.getBeanInfo(Introspector.java:164) ~[na:1.8.0_151]
	at org.thymeleaf.util.JavaScriptUtils.printObject(JavaScriptUtils.java:353) ~[thymeleaf-2.1.6.RELEASE.jar:2.1.6.RELEASE]
	at org.thymeleaf.util.JavaScriptUtils.print(JavaScriptUtils.java:184) ~[thymeleaf-2.1.6.RELEASE.jar:2.1.6.RELEASE]
	at org.thymeleaf.util.JavaScriptUtils.printKeyValue(JavaScriptUtils.java:346) ~[thymeleaf-2.1.6.RELEASE.jar:2.1.6.RELEASE]
	at org.thymeleaf.util.JavaScriptUtils.printMap(JavaScriptUtils.java:337) ~[thymeleaf-2.1.6.RELEASE.jar:2.1.6.RELEASE]
	at org.thymeleaf.util.JavaScriptUtils.printObject(JavaScriptUtils.java:365) ~[thymeleaf-2.1.6.RELEASE.jar:2.1.6.RELEASE]
	at org.thymeleaf.util.JavaScriptUtils.print(JavaScriptUtils.java:184) ~[thymeleaf-2.1.6.RELEASE.jar:2.1.6.RELEASE]
	at org.thymeleaf.util.JavaScriptUtils.printKeyValue(JavaScriptUtils.java:346) ~[thymeleaf-2.1.6.RELEASE.jar:2.1.6.RELEASE]
	at org.thymeleaf.util.JavaScriptUtils.printMap(JavaScriptUtils.java:337) ~[thymeleaf-2.1.6.RELEASE.jar:2.1.6.RELEASE]
	at org.thymeleaf.util.JavaScriptUtils.printObject(JavaScriptUtils.java:365) ~[thymeleaf-2.1.6.RELEASE.jar:2.1.6.RELEASE]

} else {

var app = new Vue({
        el: '#app',
        data: {
            user:''
        },
Everything is all right //一切正常

}

**Comment by alamhubb** [comment]
我使用spring boot jpa 将两个对象互相引用，在html中[[$ {xxx}]]获取对象，就会出现这个问题

**Comment by alamhubb** [comment]
我现在的解决办法就是使用jackson解析对象，而不是直接使用[[$ {xxx}]]在html中获取对象，请问这个问题在哪个版本里解决了，还是还未解决？

**Comment by alamhubb** [comment]
这是thymeleaf 2的bug ，升级到thymeleaf 3可以解决此bug；

thymeleaf2的时候是自己处理的json；
thymeleaf3使用的jackson，jackson可以通过使用@JsonIgnoreProperties和@JsonIgnore注解解决 两个类互相引用的问题
