### ISSUE TITLE
Spring-webflow 2.5+ is not supported

### ISSUE THREAD

**Issue by Feeel** [thymeleaf/thymeleaf-spring#208]
AjaxThymeleafViewResolver from the thymeleaf-spring5 version 3.0.11 is not compatible with spring-webflow 2.5+

AjaxThymeleafViewResolver mentioned is referencing org.springframework.js.ajax.AjaxHandler which was moved to in spring-webflow v.2.5 (https://jira.spring.io/projects/SWF/issues/SWF-1693).

Note: This is also related to the SpringJavascriptAjaxHandler.

The following exception illustrates the issue: 
```
Caused by: java.lang.IllegalStateException: Failed to introspect Class [org.thymeleaf.spring5.webflow.view.AjaxThymeleafViewResolver] from ClassLoader [ParallelWebappClassLoader
  context: ROOT
  delegate: false
----------> Parent Classloader:
java.net.URLClassLoader@55f3ddb1
]
        at org.springframework.util.ReflectionUtils.getDeclaredMethods(ReflectionUtils.java:686)
        at org.springframework.util.ReflectionUtils.doWithMethods(ReflectionUtils.java:583)
        at org.springframework.util.ReflectionUtils.doWithMethods(ReflectionUtils.java:568)
        at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.determineCandidateConstructors(AutowiredAnnotationBeanPostProcessor.java:248)
        ... 41 common frames omitted
Caused by: java.lang.NoClassDefFoundError: org/springframework/js/ajax/AjaxHandler

```

**Comment by usharik** [comment]
Looks like the same issue. Can't use `AjaxThymeleafViewResolver` if depricated module `spring-js` is not among maven dependacies. Are there any plans to fix that?

**Comment by bodtx** [comment]
same thing here, can 
`	implementation 'org.springframework.webflow:spring-webflow:2.5.1.RELEASE'`
and

`implementation 'org.springframework.webflow:spring-js:2.4.8.RELEASE`

be mixed?

**Comment by bodtx** [comment]
update : as I don't need the ajax rendering, I've removed  
`implementation 'org.springframework.webflow:spring-js:2.4.8.RELEASE`

then my resolver is 
```
@Bean
	public ThymeleafViewResolver viewResolver() {
    	ThymeleafViewResolver resolver = new ThymeleafViewResolver();
		//resolver.setViewClass(FlowAjaxThymeleafView.class);
		resolver.setTemplateEngine(templateEngine());
		return resolver;
	}
```

⚠️Note that I do not use anymore `FlowAjaxThymeleafView.class`
