### ISSUE TITLE
Avoid execution of view name as a fragment expression if view name is contained in the path or parameters of the URL

### ISSUE THREAD

**Issue by danielfernandez** [thymeleaf/thymeleaf-spring#241]
Thymeleaf allows the processing of view names as expressions when these are _fragment expressions_. They will be executed in **restricted** mode as expressed in thymeleaf/thymeleaf#809

We should modify `ThymeleafView` in order to avoid the processing of expressions when the view name is contained in the path or the parameters of the request, for further security that the `viewName` being processed does not come from direct user input in cases when a controller method has been expliclity created by app developers allowing user input to be directly used as view names.

**Comment by nabedge** [comment]
Hi.
This is a question.
Are there any relation between #221 and this issue? (or #219 ?)

**Comment by danielfernandez** [comment]
@nabedge no, they are unrelated.

**Comment by ikaakkola** [comment]
I belive this fix broke controllers using Forms that have percent-encoded values that cannot be decoded (that is, "%example%") in them and the controller endpoint that processes the form returns a "view :: fragment".

`java.lang.IllegalArgumentException: Incomplete escaping sequence in input
	at org.unbescape.uri.UriEscapeUtil.unescape(UriEscapeUtil.java:617)
	at org.unbescape.uri.UriEscape.unescapeUriQueryParam(UriEscape.java:1702)
	at org.unbescape.uri.UriEscape.unescapeUriQueryParam(UriEscape.java:1668)
	at org.thymeleaf.spring5.util.SpringRequestUtils.checkViewNameNotInRequest(SpringRequestUtils.java:55)
	at org.thymeleaf.spring5.view.ThymeleafView.renderFragment(ThymeleafView.java:275)
	at org.thymeleaf.spring5.view.ThymeleafView.render(ThymeleafView.java:190)
	at org.springframework.web.servlet.DispatcherServlet.render(DispatcherServlet.java:1373)
	at org.springframework.web.servlet.DispatcherServlet.processDispatchResult(DispatcherServlet.java:1118)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1057)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:943)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:909)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:652)`

At the time `checkViewNameNotInRequest()` is called, the request parameters are already unescaped and hence calling `UriEscape.unescapeUriQueryParam()`will fail for values that contain an invalid '%' escape sequence.
