### ISSUE TITLE
Thymeleaf-3.0.12.RELEASE : No bean resolver registered in the context to resolve access to bean

### ISSUE THREAD

**Issue by ashmeet-kandhari** [thymeleaf/thymeleaf-spring#261]
Hi Team,

We are trying to use spring beans access in [thymeleaf](https://www.thymeleaf.org/doc/articles/springmvcaccessdata.html#spring-beans)

And we are getting the following **error**

```Error on consumer: Exception evaluating SpringEL expression: \"@stringEscapeUtils1.unescapeHtml4(newsBody)\" (template: \"News/news\" - line 166, col 30)","logger_name":"com.ashmeet.test.consumer.AbstractKafkaConsumer","thread_name":"reactive-kafka-alerts-normalizer-client-id-1","level":"ERROR","level_value":40000,"stack_trace":"org.thymeleaf.exceptions.TemplateProcessingException: Exception evaluating SpringEL expression: \"@stringEscapeUtils1.unescapeHtml4(newsBody)\" (template: \"News/news\" - line 166, col 30)\r
	at org.thymeleaf.spring5.expression.SPELVariableExpressionEvaluator.evaluate(SPELVariableExpressionEvaluator.java:292)\r
	at org.thymeleaf.standard.expression.VariableExpression.executeVariableExpression(VariableExpression.java:166)\r
	at org.thymeleaf.standard.expression.SimpleExpression.executeSimple(SimpleExpression.java:66)\r
	at org.thymeleaf.standard.expression.Expression.execute(Expression.java:109)\r
	at org.thymeleaf.standard.expression.Expression.execute(Expression.java:138)\r
	at org.thymeleaf.standard.processor.StandardUtextTagProcessor.doProcess(StandardUtextTagProcessor.java:87)\r
	at org.thymeleaf.processor.element.AbstractAttributeTagProcessor.doProcess(AbstractAttributeTagProcessor.java:74)\r
	at org.thymeleaf.processor.element.AbstractElementTagProcessor.process(AbstractElementTagProcessor.java:95)\r
	at org.thymeleaf.util.ProcessorConfigurationUtils$ElementTagProcessorWrapper.process(ProcessorConfigurationUtils.java:633)\r
	at org.thymeleaf.engine.ProcessorTemplateHandler.handleOpenElement(ProcessorTemplateHandler.java:1314)\r
	at org.thymeleaf.engine.OpenElementTag.beHandled(OpenElementTag.java:205)\r
	at org.thymeleaf.engine.TemplateModel.process(TemplateModel.java:136)\r
	at org.thymeleaf.engine.TemplateManager.parseAndProcess(TemplateManager.java:661)\r
	at org.thymeleaf.TemplateEngine.process(TemplateEngine.java:1098)\r
	at org.thymeleaf.TemplateEngine.process(TemplateEngine.java:1059)\r
	at org.thymeleaf.TemplateEngine.process(TemplateEngine.java:1048)\r
	at com.ashmeet.test.template.service.TemplateService.lambda$processTemplate$0(TemplateService.java:25)\r
	at reactor.core.publisher.MonoSupplier.call(MonoSupplier.java:85)\r
	at reactor.core.publisher.FluxFlatMap.trySubscribeScalarMap(FluxFlatMap.java:127)\r
	at reactor.core.publisher.MonoFlatMap.subscribeOrReturn(MonoFlatMap.java:53)\r
	at reactor.core.publisher.Mono.subscribe(Mono.java:4135)\r
	at reactor.core.publisher.FluxMergeSequential$MergeSequentialMain.onNext(FluxMergeSequential.java:237)\r
	at reactor.core.publisher.FluxIterable$IterableSubscription.slowPath(FluxIterable.java:270)\r
	at reactor.core.publisher.FluxIterable$IterableSubscription.request(FluxIterable.java:228)\r
	at reactor.core.publisher.FluxMergeSequential$MergeSequentialMain.onSubscribe(FluxMergeSequential.java:198)\r
	at reactor.core.publisher.FluxIterable.subscribe(FluxIterable.java:164)\r
	at reactor.core.publisher.FluxIterable.subscribe(FluxIterable.java:86)\r
	at reactor.core.publisher.Flux.subscribe(Flux.java:8235)\r
	at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.subscribeNext(MonoIgnoreThen.java:255)\r
	at reactor.core.publisher.MonoIgnoreThen.subscribe(MonoIgnoreThen.java:51)\r
	at reactor.core.publisher.Mono.subscribe(Mono.java:4150)\r
	at reactor.core.publisher.FluxFlatMap.trySubscribeScalarMap(FluxFlatMap.java:203)\r
	at reactor.core.publisher.MonoFlatMap.subscribeOrReturn(MonoFlatMap.java:53)\r
	at reactor.core.publisher.Flux.subscribe(Flux.java:8221)\r
	at reactor.core.publisher.FluxFlatMap$FlatMapMain.onNext(FluxFlatMap.java:426)\r
	at reactor.core.publisher.FluxUsingWhen$UsingWhenSubscriber.onNext(FluxUsingWhen.java:358)\r
	at reactor.core.publisher.FluxUsing$UsingFuseableSubscriber.onNext(FluxUsing.java:353)\r
	at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onNext(FluxMapFuseable.java:127)\r
	at reactor.core.publisher.FluxFlattenIterable$FlattenIterableSubscriber.drainAsync(FluxFlattenIterable.java:421)\r
	at reactor.core.publisher.FluxFlattenIterable$FlattenIterableSubscriber.drain(FluxFlattenIterable.java:686)\r
	at reactor.core.publisher.FluxFlattenIterable$FlattenIterableSubscriber.onNext(FluxFlattenIterable.java:250)\r
	at reactor.core.publisher.FluxPublishOn$PublishOnSubscriber.runBackfused(FluxPublishOn.java:484)\r
	at reactor.core.publisher.FluxPublishOn$PublishOnSubscriber.run(FluxPublishOn.java:521)\r
	at reactor.core.scheduler.ExecutorScheduler$ExecutorTrackedRunnable.run(ExecutorScheduler.java:189)\r
	at reactor.core.scheduler.ImmediateScheduler$ImmediateSchedulerWorker.schedule(ImmediateScheduler.java:83)\r
	at reactor.core.scheduler.SingleWorkerScheduler.execute(SingleWorkerScheduler.java:63)\r
	at reactor.core.scheduler.ExecutorScheduler$ExecutorSchedulerWorker.schedule(ExecutorScheduler.java:242)\r
	at reactor.core.publisher.FluxPublishOn$PublishOnSubscriber.trySchedule(FluxPublishOn.java:312)\r
	at reactor.core.publisher.FluxPublishOn$PublishOnSubscriber.onNext(FluxPublishOn.java:237)\r
	at reactor.core.publisher.FluxPeekFuseable$PeekFuseableSubscriber.onNext(FluxPeekFuseable.java:210)\r
	at reactor.core.publisher.UnicastProcessor.drainRegular(UnicastProcessor.java:387)\r
	at reactor.core.publisher.UnicastProcessor.drain(UnicastProcessor.java:469)\r
	at reactor.core.publisher.UnicastProcessor.tryEmitNext(UnicastProcessor.java:337)\r
	at reactor.core.publisher.SinkManySerialized.tryEmitNext(SinkManySerialized.java:97)\r
	at reactor.core.publisher.InternalManySink.emitNext(InternalManySink.java:27)\r
	at reactor.kafka.receiver.internals.ConsumerEventLoop$PollEvent.run(ConsumerEventLoop.java:276)\r
	at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:68)\r
	at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:28)\r
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266)\r
	at java.util.concurrent.FutureTask.run(FutureTask.java)\r
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)\r
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)\r
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)\r
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)\r
	at java.lang.Thread.run(Thread.java:748)\r
Caused by: org.springframework.expression.spel.SpelEvaluationException: EL1057E: No bean resolver registered in the context to resolve access to bean 'stringEscapeUtils1'\r
	at org.springframework.expression.spel.ast.BeanReference.getValueInternal(BeanReference.java:51)\r
	at org.springframework.expression.spel.ast.CompoundExpression.getValueRef(CompoundExpression.java:55)\r
	at org.springframework.expression.spel.ast.CompoundExpression.getValueInternal(CompoundExpression.java:91)\r
	at org.springframework.expression.spel.ast.SpelNodeImpl.getValue(SpelNodeImpl.java:112)\r
	at org.springframework.expression.spel.standard.SpelExpression.getValue(SpelExpression.java:337)\r
	at org.thymeleaf.spring5.expression.SPELVariableExpressionEvaluator.evaluate(SPELVariableExpressionEvaluator.java:265)\r
	... 64 common frames omitted\r
```

**Environment**
  * `spring-boot-starter-thymeleaf` which internally has `thymeleaf-spring5-3.0.12.RELEASE`
  * Environment: Spring Boot-2.5.5 
  * org.apache.commons.commons-text:1.9
  * These are the spring configs
 
**The config for thymeleaf**
```@Configuration
public class ThymeleafConfig {
 
    @Bean
    public SpringTemplateEngine springTemplateEngine() {
        SpringTemplateEngine templateEngine = new SpringTemplateEngine();
        templateEngine.addDialect(new Java8TimeDialect());
        templateEngine.addTemplateResolver(this.htmlTemplateResolver());
        return templateEngine;
    }

    @Bean
    public SpringResourceTemplateResolver htmlTemplateResolver() {
        SpringResourceTemplateResolver emailTemplateResolver = new SpringResourceTemplateResolver();
        emailTemplateResolver.setPrefix("classpath:/templates/");
        emailTemplateResolver.setSuffix(".html");
        emailTemplateResolver.setTemplateMode(TemplateMode.HTML);
        emailTemplateResolver.setCharacterEncoding(StandardCharsets.UTF_8.name());
        return emailTemplateResolver;
    }

	@Bean(name = "stringEscapeUtils1")
	public StringEscapeUtils stringEscapeUtils1() {
		return new StringEscapeUtils();
	}

}
```

**My Template service**
```@Component
public class TemplateService implements ITemplateService {
    @Autowired
    private SpringTemplateEngine templateEngine;

    public TemplateService() {
    }

    public Mono<String> processTemplate(Map<String, Object> valueMap) {
        return Mono.fromSupplier(() -> {
            Context context = new Context();
            context.setVariables(valueMap);
            return this.templateEngine.process((String)valueMap.get("templateName"), context);
        });
    }
```

**Sample html template**
```
<div align=left
                             style='text-align: left; color: #000000; font-size: 12px; font-family: Arial, Helvetica;'
                             th:utext="${@stringEscapeUtils1.unescapeHtml4(newsBody)}"></div>
```

**Use Case**
We want to access the commons-text library's StringEscapeUtils.unescapeHtml4() static method. But as the access to static methods was removed from Thymeleaf [Issue](https://github.com/thymeleaf/thymeleaf/issues/809), we went ahead by creating a spring bean

**Comment by ultraq** [comment]
Since you're using `spring-boot-starter-thymeleaf`, that feels like a lot of config for adding your own bean.  I wonder then if something about it might be causing issues 🤔   `spring-boot-starter-thymeleaf` already configures the Thymeleaf template engine and template resolver, so to add a bean all you'll need for config is:

```java
@Configuration
public class ThymeleafConfig {

  @Bean
  public StringEscapeUtils stringEscapeUtils1() {
    return new StringEscapeUtils();
  }
}
```

Then in your template you can access the bean: `<div th:utext="${@stringEscapeUtils1.unescapeHtml4(newsBody)}"></div>`.

**Comment by ashmeet-kandhari** [comment]
Hi @ultraq ,

I tried again by creating a clean project with no extra dependencies

```
@Configuration
public class AppConfig {
    @Bean(name = "stringEscapeUtils1")
    public StringEscapeUtils stringEscapeUtils1() {
        return new StringEscapeUtils();
    }
}
```
```
@Service
public class ThymeleafService {

    SpringTemplateEngine templateEngine;

   
    public ThymeleafService(SpringTemplateEngine templateEngine) {
        this.templateEngine = templateEngine;
    }

    @PostConstruct
    public void runTemplateService(){
        String s2 = "\u0026lt;p\u0026gt;This is a test:\u0026lt;/p\u0026gt;";
        Context context = new Context();
        context.setVariable("newsBody", s2);
        System.out.println(templateEngine.process("news", context));
    }
}

```


Still getting the same error.

**Comment by danielfernandez** [comment]
I've re-tested this scenario both with Spring MVC and WebFlow applications and it works as expected. I'm closing this for now. Please reopen providing a testing application that fails if necessary.

**Comment by wangqiang1588** [comment]
follow https://www.mobibrw.com/2023/37590

`
Context context = new Context();
context.setVariables(dataMap);

ThymeleafEvaluationContext tec = new ThymeleafEvaluationContext(applicationContext, null);
dataMap.put(ThymeleafEvaluationContext.THYMELEAF_EVALUATION_CONTEXT_CONTEXT_VARIABLE_NAME, tec);
templateEngine.process(templateName, context);
`

**Comment by turboezh** [comment]
@danielfernandez, It is not obvious that bean resolution is not working outside MVC (without `ThymeleafView`) and the context must be manually filled with `ThymeleafEvaluationContext` as @wangqiang1588 pointed.
I think it is worth to document such a behavior.
