### ISSUE TITLE
WebbappClassLoader error - when reloading an application

### ISSUE THREAD

**Issue by Chropez** [thymeleaf/thymeleaf-spring#40]
I get the error below when I reload an application doing touch on the web.xml or through the tomcat manager.

I've reproduced this error in the Booking MVC - project. The error occurs even with the latest versions of Spring/Thymeleaf.
- Deploy Booking MVC.
- Move all the jars in wtpwebapps/booking-mvc/WEB-INF/lib to Tomcat-dir/lib (Our project needs to be this way)
- Write a static function anywhere in any class.
- In the html, access that static function. In our case we write :

```
<p
th:text="${T(org.springframework.webflow.samples.SomeClass).getSomeOtherClass('personToThank').sayThanks()}">
</p>
```
- Run the server.
- Navigate to the page with the static function.
- Touch your web.xml on the  wtpwebapps/booking-mvc/WEB-INF/web.xml or do a change and resave it.
- The application will reload.
- Navigate to the page with the static function and you'll get the following error:

```
INFO: Illegal access: this web application instance has been stopped already.  Could not load org.springframework.webflow.samples.SomeClass.  The even
tual following stack trace is caused by an error thrown for debugging purposes as well as to attempt to terminate the thread which caused the illegal 
access, and has no functional impact.
java.lang.IllegalStateException
    at org.apache.catalina.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1600)
    at org.apache.catalina.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1559)
    at org.springframework.expression.spel.support.StandardTypeLocator.findType(StandardTypeLocator.java:65)
    at org.springframework.expression.spel.ExpressionState.findType(ExpressionState.java:137)
    at org.springframework.expression.spel.ast.TypeReference.getValueInternal(TypeReference.java:56)
    at org.springframework.expression.spel.ast.CompoundExpression.getValueRef(CompoundExpression.java:48)
    at org.springframework.expression.spel.ast.CompoundExpression.getValueInternal(CompoundExpression.java:81)
    at org.springframework.expression.spel.ast.SpelNodeImpl.getValue(SpelNodeImpl.java:93)
    at org.springframework.expression.spel.standard.SpelExpression.getValue(SpelExpression.java:94)
    at org.thymeleaf.spring3.expression.SpelVariableExpressionEvaluator.evaluate(SpelVariableExpressionEvaluator.java:94)
    at org.thymeleaf.standard.expression.VariableExpression.executeVariable(VariableExpression.java:115)
    at org.thymeleaf.standard.expression.SimpleExpression.executeSimple(SimpleExpression.java:393)
    at org.thymeleaf.standard.expression.Expression.execute(Expression.java:230)
    at org.thymeleaf.standard.expression.StandardExpressionExecutor.executeExpression(StandardExpressionExecutor.java:62)
    at org.thymeleaf.standard.expression.StandardExpressionProcessor.executeExpression(StandardExpressionProcessor.java:124)
    at org.thymeleaf.standard.expression.StandardExpressionProcessor.processExpression(StandardExpressionProcessor.java:142)
    at org.thymeleaf.standard.processor.attr.AbstractStandardTextChildModifierAttrProcessor.getText(AbstractStandardTextChildModifierAttrProcessor.java:6
0)
    at org.thymeleaf.processor.attr.AbstractTextChildModifierAttrProcessor.getModifiedChildren(AbstractTextChildModifierAttrProcessor.java:59)
    at org.thymeleaf.processor.attr.AbstractChildrenModifierAttrProcessor.processAttribute(AbstractChildrenModifierAttrProcessor.java:58)
    at org.thymeleaf.processor.attr.AbstractAttrProcessor.doProcess(AbstractAttrProcessor.java:74)
    at org.thymeleaf.processor.AbstractProcessor.process(AbstractProcessor.java:212)
    at org.thymeleaf.dom.Node.applyNextProcessor(Node.java:914)
    at org.thymeleaf.dom.Node.processNode(Node.java:875)
    at org.thymeleaf.dom.NestableNode.computeNextChild(NestableNode.java:639)
    at org.thymeleaf.dom.NestableNode.doAdditionalProcess(NestableNode.java:621)
    at org.thymeleaf.dom.Node.processNode(Node.java:894)
    at org.thymeleaf.dom.NestableNode.computeNextChild(NestableNode.java:639)
    at org.thymeleaf.dom.NestableNode.doAdditionalProcess(NestableNode.java:621)
    at org.thymeleaf.dom.Node.processNode(Node.java:894)
    at org.thymeleaf.dom.Document.process(Document.java:93)
    at org.thymeleaf.TemplateEngine.process(TemplateEngine.java:1243)
    at org.thymeleaf.TemplateEngine.process(TemplateEngine.java:1148)
    at org.thymeleaf.extras.tiles2.renderer.ThymeleafAttributeRenderer.write(ThymeleafAttributeRenderer.java:149)
    at org.apache.tiles.renderer.impl.AbstractBaseAttributeRenderer.render(AbstractBaseAttributeRenderer.java:106)
    at org.thymeleaf.extras.tiles2.renderer.MetadataCleaningAttributeRendererWrapper.render(MetadataCleaningAttributeRendererWrapper.java:147)
    at org.apache.tiles.impl.BasicTilesContainer.render(BasicTilesContainer.java:670)
    at org.apache.tiles.impl.BasicTilesContainer.render(BasicTilesContainer.java:336)
    at org.apache.tiles.template.InsertAttributeModel.renderAttribute(InsertAttributeModel.java:210)
    at org.apache.tiles.template.InsertAttributeModel.execute(InsertAttributeModel.java:157)
    at org.thymeleaf.extras.tiles2.dialect.processor.AbstractTilesFragmentHandlingAttrProcessor.getModifiedChildren(AbstractTilesFragmentHandlingAttrProc
essor.java:169)
    at org.thymeleaf.processor.attr.AbstractChildrenModifierAttrProcessor.processAttribute(AbstractChildrenModifierAttrProcessor.java:58)
    at org.thymeleaf.processor.attr.AbstractAttrProcessor.doProcess(AbstractAttrProcessor.java:74)
    at org.thymeleaf.processor.AbstractProcessor.process(AbstractProcessor.java:212)
    at org.thymeleaf.dom.Node.applyNextProcessor(Node.java:914)
    at org.thymeleaf.dom.Node.processNode(Node.java:875)
    at org.thymeleaf.dom.NestableNode.computeNextChild(NestableNode.java:639)
    at org.thymeleaf.dom.NestableNode.doAdditionalProcess(NestableNode.java:621)
    at org.thymeleaf.dom.Node.processNode(Node.java:894)
    at org.thymeleaf.dom.NestableNode.computeNextChild(NestableNode.java:639)
    at org.thymeleaf.dom.NestableNode.doAdditionalProcess(NestableNode.java:621)
    at org.thymeleaf.dom.Node.processNode(Node.java:894)
    at org.thymeleaf.dom.NestableNode.computeNextChild(NestableNode.java:639)
    at org.thymeleaf.dom.NestableNode.doAdditionalProcess(NestableNode.java:621)
    at org.thymeleaf.dom.Node.processNode(Node.java:894)
    at org.thymeleaf.dom.NestableNode.computeNextChild(NestableNode.java:639)
    at org.thymeleaf.dom.NestableNode.doAdditionalProcess(NestableNode.java:621)
    at org.thymeleaf.dom.Node.processNode(Node.java:894)
    at org.thymeleaf.dom.NestableNode.computeNextChild(NestableNode.java:639)
    at org.thymeleaf.dom.NestableNode.doAdditionalProcess(NestableNode.java:621)
    at org.thymeleaf.dom.Node.processNode(Node.java:894)
    at org.thymeleaf.dom.Document.process(Document.java:93)
    at org.thymeleaf.TemplateEngine.process(TemplateEngine.java:1243)
    at org.thymeleaf.TemplateEngine.process(TemplateEngine.java:1148)
    at org.thymeleaf.extras.tiles2.renderer.ThymeleafAttributeRenderer.write(ThymeleafAttributeRenderer.java:149)
    at org.apache.tiles.renderer.impl.AbstractBaseAttributeRenderer.render(AbstractBaseAttributeRenderer.java:106)
    at org.thymeleaf.extras.tiles2.renderer.MetadataCleaningAttributeRendererWrapper.render(MetadataCleaningAttributeRendererWrapper.java:111)
    at org.apache.tiles.impl.BasicTilesContainer.render(BasicTilesContainer.java:670)
    at org.apache.tiles.impl.BasicTilesContainer.render(BasicTilesContainer.java:690)
    at org.apache.tiles.impl.BasicTilesContainer.render(BasicTilesContainer.java:644)
    at org.apache.tiles.impl.BasicTilesContainer.render(BasicTilesContainer.java:627)
    at org.apache.tiles.impl.BasicTilesContainer.render(BasicTilesContainer.java:321)
    at org.thymeleaf.extras.tiles2.spring.web.view.ThymeleafTilesView.render(ThymeleafTilesView.java:91)
    at org.thymeleaf.extras.tiles2.spring.web.view.AjaxThymeleafTilesView.render(AjaxThymeleafTilesView.java:193)
    at org.springframework.web.servlet.DispatcherServlet.render(DispatcherServlet.java:1208)
    at org.springframework.web.servlet.DispatcherServlet.processDispatchResult(DispatcherServlet.java:992)
    at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:939)
    at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:856)
    at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:920)
    at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:816)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:621)
    at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:801)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:722)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:305)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
    at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330)
    at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:118)
    at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:84)
    at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
    at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:113)
    at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
    at org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:103)
    at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
    at org.springframework.security.web.authentication.AnonymousAuthenticationFilter.doFilter(AnonymousAuthenticationFilter.java:113)
    at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
    at org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter.doFilter(SecurityContextHolderAwareRequestFilter.java:54)
    at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
    at org.springframework.security.web.savedrequest.RequestCacheAwareFilter.doFilter(RequestCacheAwareFilter.java:45)
    at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
    at org.springframework.security.web.authentication.www.BasicAuthenticationFilter.doFilter(BasicAuthenticationFilter.java:150)
    at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
    at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:183)
    at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
    at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:105)
    at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
    at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:87)
    at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
    at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:192)
    at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:160)
    at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:346)
    at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:259)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:243)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
    at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:77)
    at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:243)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
    at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:222)
    at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:123)
    at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:472)
    at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:168)
    at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:99)
    at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:929)
    at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:118)
    at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:407)
    at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1002)
    at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:585)
    at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:310)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1110)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603)
    at java.lang.Thread.run(Thread.java:722)
```

If the thymeleaf-spring3, and the other thymeleaf-extras are in wtpwebapps/booking-mvc/WEB-INF/lib this error will never occur. 

I Hope I've got it all down :)
Thanks for the awesome job you do with thymeleaf!

**Comment by danielfernandez** [comment]
This doesn't seem like a thymeleaf issue. The error is being found by Spring's SpringEL expression engine, most probably when it tries to find the `SomeClass` class you are including in that `T(....)` expression.

This looks more like a classloader hierarchy problem with your Tomcat setup. Class loaders in Tomcat are hierarchical, and their delegation scheme works inversely to the default. Whereas default class loaders are "delegate first, find locally last", Tomcat's are "find locally first, delegate last".

So your webapp's class loader (`/WEB-INF/lib` and `/WEB-INF/classes`) delegates to the Tomcat _shared_ classloader (for all webapps), and the Tomcat _shared_ classloader delegates to Tomcat's _common_ classloader (for all webapps plus the Tomcat Catalina engine itself), which is the one using `$TOMCAT_HOME/lib` as its classpath.

And this delegation is one way, so the webapp class loader using `/WEB-INF/lib` can see and use classes in `$TOMCAT_HOME/lib`, but the opposite is not true. So if when moving thymeleaf to `$TOMCAT_HOME/lib` you carried the spring libraries with it (which you probably did), these Spring libraries --including the SpringEL engine-- will not be able to find your `SomeClass` class if it is located in `/WEB-INF/lib`.

This could probably be solved by making the SpringEL engine look for classes using the thread's associated classloader instead of the class-local one, but I don't have enough understanding on how spring manages its classloaders internally to be able to point you in the right direction here.
