### ISSUE TITLE
th:errorclass throws exception on nested values

### ISSUE THREAD

**Issue by lightoze** [thymeleaf/thymeleaf-spring#66]
Example HTML is as follows:

```
<div th:each="app,row : ${form.applications}" th:object="${form.applications[__${row.index}__]}">
  <input type="text" th:field="*{recommendedSum}" th:errorclass="has-error"/>
</div>
```

When th:errorclass is added, it produces an exception:

```
org.springframework.beans.NotReadablePropertyException: Invalid property 'applications[0].applications[0]' of bean class [...GrantApplicationForm]: Bean property 'applications[0].applications[0]' is not readable or has an invalid getter method: Does the return type of the getter match the parameter type of the setter?
        at org.springframework.beans.BeanWrapperImpl.getPropertyValue(BeanWrapperImpl.java:729)
        at org.springframework.beans.BeanWrapperImpl.getNestedBeanWrapper(BeanWrapperImpl.java:576)
        at org.springframework.beans.BeanWrapperImpl.getBeanWrapperForPropertyPath(BeanWrapperImpl.java:553)
        at org.springframework.beans.BeanWrapperImpl.getBeanWrapperForPropertyPath(BeanWrapperImpl.java:554)
        at org.springframework.beans.BeanWrapperImpl.getPropertyValue(BeanWrapperImpl.java:719)
        at org.springframework.validation.AbstractPropertyBindingResult.getActualFieldValue(AbstractPropertyBindingResult.java:99)
        at org.springframework.validation.AbstractBindingResult.getFieldValue(AbstractBindingResult.java:219)
        at org.springframework.web.servlet.support.BindStatus.<init>(BindStatus.java:120)
        at org.thymeleaf.spring3.util.FieldUtils.getBindStatusFromParsedExpression(FieldUtils.java:348)
        at org.thymeleaf.spring3.util.FieldUtils.getBindStatus(FieldUtils.java:288)
        at org.thymeleaf.spring3.util.FieldUtils.getBindStatus(FieldUtils.java:260)
        at org.thymeleaf.spring3.util.FieldUtils.checkErrors(FieldUtils.java:225)
        at org.thymeleaf.spring3.util.FieldUtils.hasErrors(FieldUtils.java:84)
        at org.thymeleaf.spring3.processor.attr.SpringErrorClassAttrProcessor.getTargetAttributeValue(SpringErrorClassAttrProcessor.java:87)
        at org.thymeleaf.processor.attr.AbstractSingleAttributeModifierAttrProcessor.getModifiedAttributeValues(AbstractSingleAttributeModifierAttrProcessor.java:59)
        at org.thymeleaf.processor.attr.AbstractAttributeModifierAttrProcessor.processAttribute(AbstractAttributeModifierAttrProcessor.java:61)
        at org.thymeleaf.processor.attr.AbstractAttrProcessor.doProcess(AbstractAttrProcessor.java:87)
        at org.thymeleaf.processor.AbstractProcessor.process(AbstractProcessor.java:212)
        at org.thymeleaf.dom.Node.applyNextProcessor(Node.java:1016)
        at org.thymeleaf.dom.Node.processNode(Node.java:971)
```

Debugging shows that it incorrectly calculates field expression when checking for errors: `form.applications[0].applications[0].recommendedSum`

Replacing it with `th:classappend="${#fields.hasErrors('recommendedSum')}? has-error"` works as a workaround.

**Comment by danielfernandez** [comment]
Fixed! This was actually a quite interesting one. Thanks!

Updated 2.1.4-SNASPSHOT
