### ISSUE TITLE
Thymeleaf concurency error with StandardCacheManager

### ISSUE THREAD

**Issue by kelokelo** [thymeleaf/thymeleaf-spring#83]
When I use th:object and th:each on page loaded concurrently by few users, thymeleaf throws errors. I use default config (with StandardCacheManager).

Example code to recreate error: https://github.com/kelokelo/Thymeleaf-error

Thymeleaf throw errors:

```
SEVERE: Servlet.service() for servlet [spring] in context with path [] threw exception [Request processing failed; nested exception is org.thymeleaf.exceptions.TemplateProcessingException: Exception evaluating SpringEL expression: "prices" (page_element:9)] with root cause
java.lang.NullPointerException
        at org.springframework.expression.spel.ast.PropertyOrFieldReference.getValueInternal(PropertyOrFieldReference.java:84)
        at org.springframework.expression.spel.ast.SpelNodeImpl.getValue(SpelNodeImpl.java:115)
        at org.springframework.expression.spel.standard.SpelExpression.getValue(SpelExpression.java:265)
        at org.thymeleaf.spring4.expression.SpelVariableExpressionEvaluator.evaluate(SpelVariableExpressionEvaluator.java:139)
        at org.thymeleaf.standard.expression.SelectionVariableExpression.executeSelectionVariable(SelectionVariableExpression.java:146)
        at org.thymeleaf.standard.expression.SimpleExpression.executeSimple(SimpleExpression.java:80)
        at org.thymeleaf.standard.expression.Expression.execute(Expression.java:103)
        at org.thymeleaf.standard.expression.Expression.execute(Expression.java:133)
        at org.thymeleaf.standard.expression.Expression.execute(Expression.java:120)
        at org.thymeleaf.standard.fragment.StandardFragmentProcessor.resolveFragmentParameters(StandardFragmentProcessor.java:154)
        at org.thymeleaf.standard.fragment.StandardFragmentProcessor.computeStandardFragmentSpec(StandardFragmentProcessor.java:98)
        at org.thymeleaf.standard.processor.attr.AbstractStandardFragmentHandlingAttrProcessor.computeFragment(AbstractStandardFragmentHandlingAttrProcessor.java:68)
        at org.thymeleaf.processor.attr.AbstractFragmentHandlingAttrProcessor.processAttribute(AbstractFragmentHandlingAttrProcessor.java:63)
        at org.thymeleaf.processor.attr.AbstractAttrProcessor.doProcess(AbstractAttrProcessor.java:87)
        at org.thymeleaf.processor.AbstractProcessor.process(AbstractProcessor.java:212)
        at org.thymeleaf.dom.Node.applyNextProcessor(Node.java:1017)
        at org.thymeleaf.dom.Node.processNode(Node.java:972)
        at org.thymeleaf.dom.NestableNode.computeNextChild(NestableNode.java:695)
        at org.thymeleaf.dom.NestableNode.doAdditionalProcess(NestableNode.java:668)
        at org.thymeleaf.dom.Node.processNode(Node.java:990)
        at org.thymeleaf.dom.NestableNode.computeNextChild(NestableNode.java:695)
        at org.thymeleaf.dom.NestableNode.doAdditionalProcess(NestableNode.java:668)
        at org.thymeleaf.dom.Node.processNode(Node.java:990)
        at org.thymeleaf.dom.NestableNode.computeNextChild(NestableNode.java:695)
        at org.thymeleaf.dom.NestableNode.doAdditionalProcess(NestableNode.java:668)
        at org.thymeleaf.dom.Node.processNode(Node.java:990)
        at org.thymeleaf.dom.NestableNode.computeNextChild(NestableNode.java:695)
        at org.thymeleaf.dom.NestableNode.doAdditionalProcess(NestableNode.java:668)
        at org.thymeleaf.dom.Node.processNode(Node.java:990)
        at org.thymeleaf.dom.Document.process(Document.java:93)
        at org.thymeleaf.TemplateEngine.process(TemplateEngine.java:1155)
        at org.thymeleaf.TemplateEngine.process(TemplateEngine.java:1060)
        at org.thymeleaf.TemplateEngine.process(TemplateEngine.java:1011)
        at org.thymeleaf.spring4.view.ThymeleafView.renderFragment(ThymeleafView.java:335)
        at org.thymeleaf.spring4.view.ThymeleafView.render(ThymeleafView.java:190)
        at org.springframework.web.servlet.DispatcherServlet.render(DispatcherServlet.java:1228)
        at org.springframework.web.servlet.DispatcherServlet.processDispatchResult(DispatcherServlet.java:1011)
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:955)
        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:877)
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:961)
        at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:852)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:621)
        at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:837)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:728)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:305)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:243)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:222)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:123)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:502)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:171)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:100)
        at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:953)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:118)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:408)
        at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1041)
        at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:603)
        at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:312)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)

```

**Comment by RAvontuur** [comment]
I really would like this issue solved, as I daily see simular stack traces on production servers, without being able to reproduce them. Thanks a lot for this reproduction path!

After a bit of experimentation, I found that the following code change also works:

in class SpelVariableExpressionEvaluator (line139), add a synchronized block:

``` java
            if (!expContext.getPerformTypeConversion()) {
                synchronized (exp) {
                    return exp.getValue(evaluationContext, evaluationRoot);
                }
            }
```

explanation:
The cacheManager shares SpelExpression objects over multiple threads. These threads could possibly change concurrently the shared field ast.cachedReadAccessor, which happens in class PropertyOrFieldReference.

Is there a way to prevent the use of 'synchronized'?

**Comment by kelokelo** [comment]
As a workaround we just remove usage of th:object tag. And errors don't show on production. 
But for future, I believe the best solution will be fix the StandardCacheManager

**Comment by kelokelo** [comment]
We can also disable cache manager but is not a case for production:)

**Comment by RAvontuur** [comment]
Fixing the StandardCacheManager could be done by creating a separate cache for each thread in order to prevent sharing SpelExpression objects. Or, do you see a another solution?

**Comment by RAvontuur** [comment]
After having discussed this issue with my colleagues, we came to the conclusion that this issue is best solved by modifications of code in the Spring Framework, and not in Thymeleaf.
Performance tests on alternatives based on the use of 'synchonized' or 'thread local storage' showed much too high performance penalties.
The proposed solution showed no performance degradation.

You can find and test the solution on my fork of Kekelo's project:
https://github.com/RAvontuur/Thymeleaf-error/tree/solution-SpringFramework 

May someone review this solution?

**Comment by RAvontuur** [comment]
I just created an issue in the Spring project:
https://jira.spring.io/browse/SPR-13023
Hopefully will this lead to a solution for this issue.

**Comment by RAvontuur** [comment]
This issue may be closed, as it will be resolved in Spring-release 4.1.7.
see https://jira.spring.io/browse/SPR-13023

**Comment by ultraq** [comment]
Oh wow, nice investigation guys :+1:

**Comment by danielfernandez** [comment]
OK, so this was introduced in 4.1 when they added expression compilation, that's why my tests had always shown `SpelExpression` objects as thread-safe, which is what IMHO they should be from the moment they are meant to be pre-parsed and cached...

Thanks so much for all the effort diagnosing and reporting this to the Spring team.
